# Generated by Django 5.0.7 on 2024-08-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(blank=True, null=True)),
                ('english_name', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('popularity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
